repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.81.0
    hooks:
      - id: terraform_fmt
      - id: terraform_providers_lock
        args:
          - --args=-platform=linux_amd64
          - --args=-platform=windows_amd64
      - id: terraform_validate
      - id: terraform_tflint
        args:
          - --args=--module
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
      - id: terraform_tfsec
        args:
          - --args=--exclude-downloaded-modules
      - id: terraform_checkov
        args:
          - --args=--skip-check CKV_TF_1

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: no-commit-to-branch

      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: pretty-format-json

      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
      - id: detect-private-key
